### ISSUE TITLE
Add brew cask

### ISSUE THREAD

**Issue by SolidRhino** [straxhaber/homebrew-auto-update#1]
Can you please add brew cask? This is helpful for upgrading that applications.

**Comment by straxhaber** [comment]
I am closing this issue in favor of https://github.com/caskroom/homebrew-cask/issues/4678. Cask upgrading isn't supported by [homebrew-cask](https://github.com/caskroom/homebrew-cask) itself, so we can't support it here.

Also, it is worth noting that [homebrew-auto-update](https://github.com/straxhaber/homebrew-auto-update) runs `brew update`, which now updates cask formulas as well. In fact, if you run `brew cask help`, it says that `brew cask update` is "a synonym for 'brew update'".

Please feel free to comment further if you think there is something we can actually do before [homebrew-cask](https://github.com/caskroom/homebrew-cask) supports upgrading. I'd also welcome any pull requests (although comments are okay as well).
